add_newline = true
command_timeout = 5000

[battery]
disabled = true

[character]
success_symbol = "[âœ](bold green) "
error_symbol = "[âœ](bold red) "

[directory]
truncation_length = 3
truncation_symbol = "â€¦/"
home_symbol = "~"
read_only = " "
style = "blue bold"

[git_branch]
always_show_remote = true
symbol = "ğŸŒ± "
style = "purple bold"

[git_commit]
only_detached = false
style = "bold green"

[git_metrics]
disabled = false
added_style = "bold blue"
deleted_style = "bold red"
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "cyan bold"
conflicted = "ğŸ³"
up_to_date = "âœ“"
untracked = "ğŸ¤·"
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = '[++\($count\)](green)'
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"

[nodejs]
symbol = "â‡ï¸ "
detect_files = ["package.json", ".node-version"]
style = "bold green"

[python]
python_binary = "python3"
symbol = "ğŸ "
style = "bold yellow"

[rust]
symbol = "ğŸ¦€ "
style = "bold red"

[package]
disabled = false
symbol = "ğŸ“¦ "

[cmd_duration]
min_time = 2_000
format = "took [$duration](bold yellow)"

[memory_usage]
disabled = false
threshold = 70
symbol = "ğŸ"
style = "bold dimmed white"

[time]
disabled = false
format = 'ğŸ•™[\[ $time \]]($style) '
time_format = "%T"
style = "bold yellow"