[character]
success_symbol = "[âœ](bold green) "
error_symbol = "[âœ](bold red) "

[git_branch]
always_show_remote = true
symbol = "ğŸŒ± "

[git_commit]
only_detached = false
style = "bold green"

[git_metrics]
disabled = true
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[nodejs]
symbol = "â‡ï¸  "

[python]
python_binary = "python3"
